### ISSUE TITLE
Cabal error on findsymbol in stack project

### ISSUE THREAD

**Issue by jonascarpay** [hdevtools/hdevtools#29]
When running findsymbol on a stack project with at least one dependency other than base, I'm getting an error similar to #5 
`> stack exec --no-ghc-package-path hdevtools -- findsymbol reverse`
`Cabal error: At least the following dependencies are missing:
    microlens -any`
I used microlens in this example, but if I add another package as a dependency in my .cabal file, it'll throw an error message for that package
- If base is the only dependency, everything works as expected
- `hdevtools check` works as expected
- I don't have any GHC/Cabal installs other than the one from stack

**Comment by ch1bo** [comment]
Alright thanks for reporting! Maybe I can pick up some loose ends this weekend and also look into this.

**Comment by jonascarpay** [comment]
Thanks for your quick response! Let me know if you need any more information.

**Comment by ch1bo** [comment]
Alright, can you try to checkout the `stack-ghc-libdir` branch, install that version using `stack install` and try this again? This version does not require execution `stack exec` anymore, so a direct invocation should find your compiler and packages correctly.

**Comment by jonascarpay** [comment]
This works! Thanks a lot!

**Comment by ch1bo** [comment]
Alright, I guess I will release soon then!
