### ISSUE TITLE
Using hdevtools with Hspec: Could not find module ‘Test.Hspec’ It is a member of the hidden package

### ISSUE THREAD

**Issue by greglearns** [hdevtools/hdevtools#4]
I've installed hdevtools using "stack install hdevtools" which installs hdevtools into the global "unassigned" stack. That works fine.

However, I'm using hdevtools to check my spec files, and in my test/Spec.hs file, I have the following:
```
module Hashboard.ModelSpec (main, spec) where
import Test.Hspec  -- this line causes an Hdevtools error
```
The message from Hdevtools is: Could not find module ‘Test.Hspec’ It is a member of the hidden package ‘hspec-2.2.1@hspec_4R8oqeKmp2qHiEwtLGb3ih’.

Any ideas?

By the way, thank you so much for Hdevtools, it's wonderful!

Greg

**Comment by ch1bo** [comment]
Which version of hdevtoola did you install? `hdevtools --version` Which resolver is in your global stack config? 

Considering modules of test-suites and benchmarks in cabal file was added with 0.1.2.2 which I pushed only recently. As of lts-4.2 or a nightly a week ago 0.1.2.2 should be available via stackage.

**Comment by greglearns** [comment]
I was running these versions:
hdevtools: version 0.1.2.1 (ghc-7.10.3-x86_64-darwin, cabal-1.22.6.0)
resolver: lts-4.1

I just changed the resolver to lts-4.2 and did "stack install hdevtools"
and now the problem is fixed. Thank you!

**Comment by ch1bo** [comment]
You're welcome. Is this resolved then?

**Comment by greglearns** [comment]
It is resolved. Thank you!

Hdevtools really is helpful
