### ISSUE TITLE
could not find installed module 

### ISSUE THREAD

**Issue by Alok** [hdevtools/hdevtools#45]
I have Pandoc installed globally (since I use it for general file format conversion, not as part of a project), and I'm trying to write a filter for it. This requires `import Text.Pandoc`. In `ghci`, I can import it just fine, but `hdevtools` gives the following error:

```
Could not find moudle 'Text.Pandoc.JSON'. Use -v to see a list of the files searched for.
```

Does `hdevtools` have any way of picking up global packages?

**Comment by ch1bo** [comment]
⁣Hey this sounds a lot like an existing issue. How did you install pandoc, i.e. where is it located?

**Comment by Alok** [comment]
I installed pandoc with `stack` into `~/.local/bin` (the standard global bin for `stack` packages).
