### ISSUE TITLE
Cut New Release

### ISSUE THREAD

**Issue by ChrisCoffey** [hdevtools/hdevtools#46]
Please cut a new release which includes #38 to support TH

**Comment by ch1bo** [comment]
Currently in Australia road tripping..maybe @rjalla can?⁣

**Comment by ch1bo** [comment]
Sorry for the delay, version 0.1.5.0 should be available on hackage and soon in stackage snapshots http://hackage.haskell.org/package/hdevtools

**Comment by ranjitjhala** [comment]
Thanks @ch1bo !
