### ISSUE TITLE
Cabal error: At least the following dependencies are missing

### ISSUE THREAD

**Issue by damiencourousse** [hdevtools/hdevtools#5]
hello, 

I have successfully used hdevtools in the past with Cabal, but I have this problem since I moved to stack:
```
✓$ hdevtools check lib/Version.hs 
Cabal error: At least the following dependencies are missing:
    ConfigFile -any,
    Diff -any,
    MissingH -any,
```

The problem is the same if hdevtools is called as follows, from the source directory of my Haskell project:
```
$ stack exec --no-ghc-package-path hdevtools -- check lib/ConfigPath.hs
Cabal error: At least the following dependencies are missing:
    ConfigFile -any,
    Diff -any,
    MissingH -any,
```

I have installed hdevtools with stack (`stack install hdevtools`). I use this version:
```
$ hdevtools --version
hdevtools: version 0.1.2.2 (ghc-7.10.3-x86_64-linux, cabal-1.22.6.0)
$ which hdevtools 
/home/damien/.local/bin/hdevtools
```

A plausible reason for this might be that the version of ghc installed on my system is different of the version used on this project:
```
$ which ghc
/usr/bin/ghc
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.6.3
$ stack exec ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3
```

Any ideas?

BTW, thank you so much for this veeeery nice tool! :)

Damien

**Comment by ch1bo** [comment]
What does `stack build` output? As hdevtools just loads modules from stack package dbs it is required that dependencies are installed by other means. In this case via stack.

**Comment by damiencourousse** [comment]
`stack build` works OK.
I have a local version of acid-state because of a pending pull request:

```
$ stack clean
$ stack build
acid-state-0.14.1: unregistering (local file changes: acid-state.cabal benchmarks/loading/Benchmark.hs src-unix/FileIO.hs src/Data/Acid.hs src/Data/Aci...)
lbc-2.2.0: unregistering (missing dependencies: acid-state)
acid-state-0.14.1: configure
acid-state-0.14.1: build
acid-state-0.14.1: copy/register
lbc-2.2.0: configure
lbc-2.2.0: build
lbc-2.2.0: copy/register
Completed all 2 actions.
$ stack exec --no-ghc-package-path hdevtools -- --stop-server
Shutting down server.
$ stack exec --no-ghc-package-path hdevtools -- check lib/ConfigPath.hs
Cabal error: At least the following dependencies are missing:
    ConfigFile -any,
    Diff -any,
    MissingH -any,
(...)
```

**Comment by ch1bo** [comment]
Hm.. which stack resolver are you using? Can you post your stack.yaml or is this project even open source so I can try to reproduce the errors?

Assuming that hdevtools just doesn't find the modules because it is pointed to the wrong instance of ghc. Can you try to run `stack install hdevtools` again from your project directory?

**Comment by ch1bo** [comment]
For testing you can just set your PATH to point to the correct ghc (i.e. the one in your `$HOME/.stack/programs/...`) when you invoke `hdevtools` directly.
So no need for stack exec if you point it to your ghc..

**Comment by damiencourousse** [comment]
Using stack resolver `lts-4.2`.

stack configuration:
```
$ cat stack.yaml 
# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-4.2

# Local packages, usually specified by relative directory name
packages:
- acid-state
- '.'

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- acid-state-0.14.0.1 # sources available in ./acid-state

# Override default flag values for local packages and extra-deps
flags:
  lbc:
    test-hlint: true
    devel: false
    debug: false

# Extra package databases containing global packages
extra-package-dbs: []
```

Reinstalling hdevtools with stack does not help:
```
$ find ~/.stack -name ghc 
/home/damien/.stack/programs/x86_64-linux/ghc-7.10.3/share/doc/ghc
/home/damien/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/bin/ghc
/home/damien/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc
$ export PATH=/home/damien/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/bin:$PATH
$ stack install hdevtools
Copying from /home/damien/.stack/snapshots/x86_64-linux/lts-4.2/7.10.3/bin/hdevtools to /home/damien/.local/bin/hdevtools

Copied executables to /home/damien/.local/bin:
- hdevtools
$ ll /home/damien/.stack/snapshots/x86_64-linux/lts-4.2/7.10.3/bin
total 102244
-rwxr-xr-x 1 damien damien  9257720 janv. 23 14:53 aeson-pretty
-rwxr-xr-x 1 damien damien 15842744 janv. 30 11:47 cabal
-rwxr-xr-x 1 damien damien  2172952 janv. 23 14:48 clientsession-generate
-rwxr-xr-x 1 damien damien 59671224 janv. 23 23:01 hdevtools
-rwxr-xr-x 1 damien damien  9068376 janv. 23 14:57 json2yaml
-rwxr-xr-x 1 damien damien  8534264 janv. 23 14:57 yaml2json
$ hdevtools --version
hdevtools: version 0.1.2.2 (ghc-7.10.3-x86_64-linux, cabal-1.22.6.0)
$ which ghc
/home/damien/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/bin/ghc
$ hdevtools --stop-server
Shutting down server.
$ hdevtools check lib/Version.hs 
Cabal error: At least the following dependencies are missing:
    ConfigFile -any,
    Diff -any,
    MissingH -any,
(...)
```

**Comment by ch1bo** [comment]
That's weird, compilers and locations seem to match. Do you know the packages he reports as missing? Does hdevtools work for the acid-state sources? 

As a side note: I don't think that `acid-state` has to be listed as `extra-deps` if you have local sources.

**Comment by damiencourousse** [comment]
Yes, that's weird... 
I am using a Debian/Linux system.
These packages are not installed globally on the machine, but are installed locally by stack.

For example:
```
$ find -iname '*diff*'
./.stack-work/logs/Diff-0.3.2.log
./.stack-work/install/x86_64-linux/lts-4.2/7.10.3/flag-cache/Diff-0.3.2-c6ecff1b6130e3846fe8ae3dee97ce61
$ find -iname '*configfile*'
./.stack-work/logs/ConfigFile-1.1.4.log
./.stack-work/install/x86_64-linux/lts-4.2/7.10.3/flag-cache/ConfigFile-1.1.4-896012d130e9c2043272f4d000e147a0
```

Experimenting something more. The error is different this time. Does it give you a clue?
```
$ which hdevtools
/home/damien/.local/bin/hdevtools
$ stack exec hdevtools -- --stop-server
Shutting down server.
$ stack exec hdevtools -- --start-server --nodaemon &
[2] 4159
$ stack exec hdevtools -- check lib/Version.hs 
Configuring lbc-2.2.0...
Cabal error: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with Cabal. Use the flag --package-db to specify a package database (it can be used multiple times).
```

**Comment by ch1bo** [comment]
you missed `--no-ghc-package-path` on the last one :)

**Comment by damiencourousse** [comment]
OK sorry, let's try again. Not better:
```
$ stack exec hdevtools -- --stop-server
Shutting down server.
[2]+  Fini                    stack exec hdevtools -- --start-server --nodaemon
$ stack exec --no-ghc-package-path hdevtools -- --start-server --nodaemon & 
[2] 5384
$ stack exec --no-ghc-package-path hdevtools -- check lib/Version.hs
Configuring lbc-2.2.0...
Cabal error: At least the following dependencies are missing:
    ConfigFile -any,
    Diff -any,
    MissingH -any,
    acid-state >=0.14.1,
(...)
```

**Comment by ch1bo** [comment]
Does it work if you use the acid-state from stackage, i.e. without the local package?

**Comment by damiencourousse** [comment]
Not better, sorry.

Removing the local version of acid-state, and updating stack and cabal configurations:
```
$ rm -rf acid-state
$ LANG=C git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    acid-state
	modified:   lbc.cabal
	modified:   stack.yaml

$ LANG=C git diff
diff --git a/acid-state b/acid-state
deleted file mode 160000
index 63aee60..0000000
--- a/acid-state
+++ /dev/null
@@ -1 +0,0 @@
-Subproject commit 63aee602941d4941271717543948400ab8ede879
diff --git a/lbc.cabal b/lbc.cabal
index e2c0831..eb12c70 100644
--- a/lbc.cabal
+++ b/lbc.cabal
@@ -49,7 +49,7 @@ library
                  , Utils.Parsec
                  , Version
   build-depends:   base >= 4 && < 5
-                 , acid-state >= 0.14.1
+                 , acid-state == 0.14.*
                  , bytestring
                  , cereal
                  , ConfigFile
diff --git a/stack.yaml b/stack.yaml
index 5eb38f9..7159cf4 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -5,7 +5,6 @@ resolver: lts-4.2
 
 # Local packages, usually specified by relative directory name
 packages:
-- acid-state
 - '.'
```

Building and testing:
```
$ stack build
acid-state-0.14.1: unregistering
lbc-2.2.0: unregistering
acid-state-0.14.0: download
acid-state-0.14.0: configure
acid-state-0.14.0: build
acid-state-0.14.0: copy/register
lbc-2.2.0: configure
Configuring lbc-2.2.0...
lbc-2.2.0: build
Preprocessing library lbc-2.2.0...
(...)
In-place registering lbc-2.2.0...
Preprocessing executable 'lbc' for lbc-2.2.0...
(...)        
lbc-2.2.0: copy/register
Installing library in
/home/damien/src/lbc/.stack-work/install/x86_64-linux/lts-4.2/7.10.3/lib/x86_64-linux-ghc-7.10.3/lbc-2.2.0-HhT008pGCaRGjlINarHlvk
Installing executable(s) in
/home/damien/src/lbc/.stack-work/install/x86_64-linux/lts-4.2/7.10.3/bin
Registering lbc-2.2.0...
Completed all 2 actions.
$ stack exec hdevtools -- --stop-server
Shutting down server.
[2]+  Fini                    stack exec --no-ghc-package-path hdevtools -- --start-server --nodaemon
$ stack exec --no-ghc-package-path hdevtools -- --start-server --nodaemon & 
[2] 6120
$ stack exec --no-ghc-package-path hdevtools -- check lib/Version.hs
Configuring lbc-2.2.0...
Cabal error: At least the following dependencies are missing:
    ConfigFile -any,
    Diff -any,
    MissingH -any,
    acid-state ==0.14.*,
(...)
```

**Comment by ch1bo** [comment]
And you have only problems in the `lcb` package? How about running hdevtools in `acid-state` or something else?

**Comment by damiencourousse** [comment]
You are right. It's the same if I run hdevtools in acid-state.

**Comment by ch1bo** [comment]
Alright, I can reproduce an error after quickly unpacking `acid-state` and intializing a `stack.yaml`. For `acid-state` it seems like the `extra-dep` for `criterion` results in errors when running `hdevtools`:
```
➜ hdevtools check src/Data/Acid.hs
Cabal error: At least the following dependencies are missing:
    criterion >=0.8 && <1.1,
    random -any,
    system-fileio ==0.3.*,
    system-filepath -any
```

Which might be similar to the problem you are facing with your package. I will try to have a look on it this weekend.

**Comment by damiencourousse** [comment]
Thank you!

**Comment by ch1bo** [comment]
Alright, after checking my package dbs for `criterion` I realized that these packages are only required in a bechmark. As said previously dependant packages have to be installed prior using hdevtools. So most likely your missing packages are defined in a test-suite or benchmark section of the cabal file? If yes, `stack build --test --bench` should install these dependencies and hdevtools should work.

Now the big question is, what would you have expected? Currently hdevtools configures ghc for all targets (including tests and bechmarks), thus requiring all dependencies available.

**Comment by damiencourousse** [comment]
Thanks for your help with this issue.

My cabal file contains several sections: one library, two executables sections, and three test-suite sections. It's maybe not the cleanest solution, but at least it seems to be a good test case for `hdevtools` :).
Something like:
```
library
  hs-source-dirs:  lib
(...)
  build-depends:   base >= 4 && < 5
                 , acid-state >= 0.14.1
                 , bytestring
                 , cereal
                 , ConfigFile
                 , Diff

(...)

executable lbc
  hs-source-dirs: .
  main-is:        lbc.hs
  build-depends:  lbc
                , base >= 4 && < 5
(...)

executable lbc-webapp
(...)
  build-depends: lbc
               , base >= 4 && < 5
               , data-default
               , http-conduit
               , MissingH
(...)

test-suite doctests
  default-language: Haskell2010
  type:             exitcode-stdio-1.0
  ghc-options:      -threaded -ilib -Wall
  main-is:          tests/doctests.hs
  build-depends:    lbc, base, doctest >= 0.8

test-suite tasty
  default-language: Haskell2010
(...)

```

It's right that the previous stack builds did not enable test builds, but yet, the library and the two executables are built by default by stack. Hence their dependencies are installed and available locally. For example, the acid-state library is available but hdevtools does not find it. Same for `ConfigFile`, used in the library but not declared as a dependency of the executables. Could it be  that hdevtools does not pick all the sections of my cabal file? 

If it helps I can send you an archive of the source code.

**Comment by damiencourousse** [comment]
Could it be related to [this issue](https://github.com/bitc/hdevtools/issues/40)?

**Comment by ch1bo** [comment]
If you can share (in terms of licensing) the code that would probably the easiest way for me to reproduce your problems. 

So far I did not have any problems with hdevtools and multiple targets in a cabal file. Despite the fact that I always forget to build (install deps) once in the beginning.

**Comment by damiencourousse** [comment]
I guess I found the culprint: cabal sandboxes.

I did another test in another project. This time I got this error:
```
$ stack exec --no-ghc-package-path hdevtools -- check src/Hackup.hs 
Cabal error: '/home/damien/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc-pkg' exited with an error:
ghc-pkg: /home/damien/src/hackup/.cabal-sandbox/x86_64-linux-ghc-7.6.3-packages.conf.d: getDirectoryContents: does not exist (No such file or directory)
```
WTF? Using ghc-7.10.3, but the message says stack looks for ghc-7.6.3 packages... in a cabal sandbox. Deleted the sandbox, started a new build to install the missing dependencies, and hdevtools is happy again :)!

I could reproduce this in the first project where I encountered this problem: deleting the sandbox and building again with stack fixes the problem. Yay!

This problem was weird because stack seems to cohabit nicely with cabal sandboxes. Hence no build errors...

Thank you for your help on this.

**Comment by ch1bo** [comment]
So you had a sandbox config in your project when the original errors occurred?

**Comment by damiencourousse** [comment]
Yes

Le 2 février 2016 22:58:50 GMT+01:00, Sebastian <notifications@github.com> a écrit :
>So you had a sandbox config in your project when the original errors
>occurred? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hdevtools/hdevtools/issues/5#issuecomment-178848249

-- 
Envoyé de mon téléphone. Veuillez excuser ma brièveté.

**Comment by ch1bo** [comment]
Alright, so I regard this as closed and will have a look on how to communicate preference between cabal sandboxes and stack better.
