### ISSUE TITLE
Usge in projects that don't use cabal or stack

### ISSUE THREAD

**Issue by pacak** [hdevtools/hdevtools#58]
Current version assumes existence of stack by means of `mStackYaml <- findStackYaml dir` and cabal `mCabalFile <- findCabalFile dir >>= traverse absoluteFilePath`. For project that uses neither of those system looking for stack results in a bunch of wasted time and some strange error when stack finally finds system wide config and fails to do anything since project is not compatible with stack.

If I comment out all the attemps of looking for those two files, replace them with Nothing and provide required ghc params - hdevtools works as expected, but this makes it painful to use in a text editor that starts hdevtools automatically.

Possible solution: create a config file `.hdevtoolsrc`, add ability to read command line options from this file, add extra options to override cabal and stack files (or specify their absense). During start time `hdevtools` should look for config (the same way it looks for .cabal file) and read options from there. This should allow easy per-project overrides even for those projects that use cabal/stack without having to mess with editor's config.

I can implement following proposal. (already did, but not in a clean way). Any preferences for a config file library?

**Comment by ch1bo** [comment]
So this is resolved now, or?

**Comment by pacak** [comment]
Works for me.
