### ISSUE TITLE
Encountered missing dependencies

### ISSUE THREAD

**Issue by bengolds** [hdevtools/hdevtools#66]
I'm in a [project](https://github.com/elm-lang/elm-compiler) that uses cabal, not stack. I'm trying to get hdevtools working, and when I run `hdevtools check` or `cabal exec hdevtools check`, I get the below:
```
Cabal error: Encountered missing dependencies:
    HUnit >=1.1 && <2,
    aeson-pretty <0.8,
    binary >=0.7.0.0 && <0.8,
    edit-distance ==0.2.*,
    filemanip >=0.3.5 && <0.4,
    language-glsl >=0.0.2 && <0.3,
    test-framework >0.8 && <0.9,
    test-framework-hunit ==0.3.*,
    test-framework-quickcheck2 ==0.3.*,
    union-find ==0.2.*
```

The project builds just fine with `cabal build`, so I'm not quite sure what's going on. Any ideas?

**Comment by ch1bo** [comment]
All targets will be selected for type checking a module and thus also your tests get 'built' in hdevtools. IIRC `cabal install --enable-tests --dependencies-only` should resolve and install your deps?

⁣Sent from TypeApp ​

**Comment by bengolds** [comment]
Hmm, I tried that but I still have the same error. I've removed the test target from the cabal file, and I still get:
```
Cabal error: Encountered missing dependencies:
    aeson-pretty <0.8,
    binary >=0.7.0.0 && <0.8,
    edit-distance ==0.2.*,
    language-glsl >=0.0.2 && <0.3,
    union-find ==0.2.*
```

What's going on that it's not picking up the installed dependencies?

**Comment by ch1bo** [comment]
hm okay..where are these packages nowadays installed wirh cabal-install? you can start hdevtools with -d to double check it just sees your .cabal file and we can figure out where libs are searched for from there

⁣Sent from TypeApp ​

**Comment by bengolds** [comment]
I've solved it! I had to disable the stack integration -- it was detecting the global stack instance and using that to search for the packages.
