### ISSUE TITLE
Inconsistent behaviour between 'info' and 'modulefile'

### ISSUE THREAD

**Issue by JonnyRa** [hdevtools/hdevtools#69]
Hi,

I'm using the vim hdevtools and ale linting plugins and am finding them really useful, however the hdevtools plugin is behaving inconsistently.  I'm fairly new to haskell/stack etc and have been trying to figure out how things need to be set up to work.

I suppose part of this is about helping me to understand what the tool does/what it's model of the world is.  Its a bit of a blackbox to me at the moment and I think it would be a really useful addition to the documentation to provide this kind of information.  For instance I found the type investigation behaviour works without compilation but the linting stuff is all over the place without it... anyway that's a different story.

The problem I'm seeing is that the type investigation is working but I can't jump to declaration.  

I can observe the same behaviour when using hdevtools from the command line - I can use info to query an identifier in a file
eg 

    hdevtools info haskell-service/selenium/SeleniumTests//Simplifier.hs  makeNewUnitDiagramsSetEventsSource

 and it gives me:

    makeNewUnitDiagramsSetEventsSource ::
      Monad m =>
      UnitDiagramsSetDTT
      -> conduit-1.2.11:Data.Conduit.Internal.Conduit.Source
    m (Int, Types.OutgoingEvent.OutgoingEventDetails)
    --Defined in ‘Model.UnitDiagrams’

 however if I then use `hdevtools modulefile Model.UnitDiagrams` from the same path I get 'Module not found'.

It seems to me like hdevtools must know the module locations as it's reading them.

Is the location it gets called from important?

running hdevtools --debug I get the following from that location
    
    Cabal file: Nothing
    Stack file: Just "/home/blah/repos/blah/stack.yaml"
    Socket file: ".hdevtools.sock"

I've messed with the path there.

I'm running:
hdevtools: version 0.1.5.0 (ghc-8.0.2-x86_64-linux, cabal-1.24.2.0)

Its a big project made up of lots of different cabal projects and I'm new to it and don't really understand the structure (or the build tools!) yet but building using stack works so other haskelly stuff is able to understand how it all fits together.

**Comment by JonnyRa** [comment]
Properly reading the documentation I can see there is some stuff about paths!

**Comment by JonnyRa** [comment]
So I've read a bit of the code and (based on guesswork!) there is a difference in the calls  in runCommand - for info and type they are being passed through withTargets which uses the config which contains the stack stuff, whereas runCommand for Module file (line 238) just dives straight into calling GHC stuff.

Is there any particular reason for the difference?

Hopefully that helps!  I might have a swing at fixing it next week, but I'm supposed to be reading/working on different code right now!  Also I have zero knowledge of the library/git which will slow things down

**Comment by ch1bo** [comment]
Thanks for testing hdevtools and reporting all this! So the core of this problem seems to be that `moduleinfo` is used by your editor integration and it does not work, right?

**Comment by JonnyRa** [comment]
You're welcome!  Thanks for making such a useful tool and fixing it quickly!  Yeah looks like it.  Tbh I haven't confirmed that the [vim plugin](https://github.com/bitc/vim-hdevtools) uses that call but it looked like the only one that would have made sense, and since the behaviour matches between the two I assume that it does... haha if it doesn't I can get on to them to fix that/fix it myself!  

The bit about [ale](https://github.com/w0rp/ale) is actually irrelevant here, although it does make use of hdevtools, although I assume that one is using `check`, it also seems to work but took a bit of guess work with setting pwd in vim (which is an issue with ale) and also building everything which is where I came across the [-v issue](https://github.com/hdevtools/hdevtools/issues/68)

**Comment by ch1bo** [comment]
Have you tried the branch by any chance? I would merge it tomorrow and try to get a new version release for ghc 8.2.x support

**Comment by JonnyRa** [comment]
I didn't get round to checking the branch previously but I've just installed 0.1.6.0 using stack.

Unfortunately, I'm still getting Module not found when re-running with the new version, anything I could do to help debug?

So far I've tried running the moduleinfo command from the following places:

`projectRoot` (has a stack.yaml).  There's no code here but this is the root directory
`projectRoot/mainProject` (sees above stack.yaml, has it's own cabal) this is the main project that references otherProject where the file is.
`projectRoot/otherProject` (sees above stack.yaml, has it's own cabal) this is where the module I'm looking for lives, it is found at:
`projectRoot/otherProject/src/Model/TheFile.hs`

I've also looked at --debug for all of these calls and hdevtools can see the relevant stack/cabal files at each point

**Comment by ch1bo** [comment]
Can you try the just released 0.1.6.1? IIRC a fix for moduleinfo command is included in this.

⁣Sent from TypeApp ​

**Comment by JonnyRa** [comment]
Whoops I read the wrong version number!

**Comment by JonnyRa** [comment]
Still seeing the same output in all 3 places with the following:

hdevtools --version
hdevtools: version 0.1.6.1 (ghc-8.0.2-x86_64-linux, cabal-1.24.2.0)

**Comment by JonnyRa** [comment]
Am I using the correct syntax to call:

`hdevtools modulefile Model.Blah`
