### ISSUE TITLE
GHC.ModuleGraph redefinition in ghc 8.4.1 causes build failure

### ISSUE THREAD

**Issue by patrick96** [hdevtools/hdevtools#80]
When trying to install `hdevtools` on ArchLinux via the [AUR](https://aur.archlinux.org/packages/hdevtools/), it fails with the following error:
```
Preprocessing executable 'hdevtools' for hdevtools-0.1.6.1..
Building executable 'hdevtools' for hdevtools-0.1.6.1..
[ 1 of 13] Compiling Daemonize        ( src/Daemonize.hs, dist/build/hdevtools/hdevtools-tmp/Daemonize.dyn_o )
[ 2 of 13] Compiling FindSymbol       ( src/FindSymbol.hs, dist/build/hdevtools/hdevtools-tmp/FindSymbol.dyn_o )

src/FindSymbol.hs:40:59: error:
    • Couldn't match type ‘GHC.ModuleGraph’ with ‘[GHC.ModSummary]’
      Expected type: GHC.Ghc [GHC.ModSummary]
        Actual type: GHC.Ghc GHC.ModuleGraph
    • In the second argument of ‘(<$>)’, namely ‘GHC.getModuleGraph’
      In the second argument of ‘(=<<)’, namely
        ‘map GHC.ms_mod <$> GHC.getModuleGraph’
      In the expression:
        filterM (containsSymbol symbol)
          =<< map GHC.ms_mod <$> GHC.getModuleGraph
   |
40 |    filterM (containsSymbol symbol) =<< map GHC.ms_mod <$> GHC.getModuleGraph
   |                                                           ^^^^^^^^^^^^^^^^^^
```

The same happens, if I run the following commands inside this repo:
```bash
runhaskell Setup configure -O --enable-executable-dynamic --prefix=/usr
runhaskell Setup build
```
or even when trying to install via cabal.

`stack install hdevtools` works, but I have to run `hdevtools check` with `--nostack`, otherwise it doesn't produce any output and immediately hangs. (**EDIT:** I have just tested this again and it doesn't actually hang but just takes longer to produce some output.)

From digging around a bit, I found the commit https://github.com/ghc/ghc/commit/b8fec6950ad99cbf11cd22698b8d5ab35afb828f#diff-bc8c9b8edad6309c0e6cbf2ad7e60ebeL2621 which was introduced in ghc 8.4.1 and redefines `ModuleGraph`.

I have also found https://github.com/haskell/haddock/issues/635 which talks about this, but I don't know how relevant this is.

This would also explain why manually compiling it and cabal fail, while stack does not, because the latest stack lts uses ghc 8.2.2 which doesn't have that change and on Arch we have ghc 8.4.2.

**Comment by shepheb** [comment]
This has become more of a problem recently with stack `lts-12.0` bringing GHC 8.4 to the masses. I fixed this specific issue locally (it's not hard, `import qualified HscTypes` and use `mgModSummaries` to extract the `[ModSummary]` hdevtools needs.

But that exposes a handful of other issues that are a lot more involved and confusing to an outsider who doesn't know the GHC API. The [changelog](https://github.com/ghc/ghc/blob/df449e1744d59eef7f41e09196629bc01815e984/docs/users_guide/8.4.1-notes.rst#ghc-library) has some advice on the changed types, and maintaining backwards compatibility.

**Comment by ch1bo** [comment]
Fixed with #83

**Comment by kuznero** [comment]
What are the plans for pushing it to hackage and stackage?

**Comment by ch1bo** [comment]
I can make a release soon. maybe tonight or on the weekend

**Comment by kuznero** [comment]
Sounds great! Thanks, @ch1bo !
