### ISSUE TITLE
Extremely poor performance when using Stack

### ISSUE THREAD

**Issue by jeremyjh** [hdevtools/hdevtools#9]
If I have a stack.yaml file in my project tree, performing a check takes several orders of magnitude longer than if I do not have this file, given the same commands. It takes this time on every invocation.

I am using:
hdevtools: version 0.1.2.2 (ghc-7.10.3-x86_64-linux, cabal-1.22.7.0)

Summary: with stack elapsed time is 0:01.57elapsed, with cabal sandbox arguments it is 0:00.10elapsed. 

The times listed are after the second invocation (e.g. the server process is already running):

Here is the time using the cabal sandbox (I have to rename the stack.yaml so it doesn't get used):

```shell
/usr/bin/time hdevtools check -g -Wall -g -no-user-package-db -g-package-db/home/jeremy/repos/haskell/distributed-process-lifted/.cabal-sandbox/x86_64-linux-ghc-7.10.3-packages.conf.d -g-i/home/jeremy/repos/haskell/distributed-process-lifted/src/ -g-i/home/jeremy/repos/haskell/distributed-process-lifted/dist/build -g-i/home/jeremy/repos/haskell/distributed-process-lifted/dist/build/autogen -g-i/home/jeremy/repos/haskell/distributed-process-lifted/.stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build -g-i/home/jeremy/repos/haskell/distributed-process-lifted/.stack-work/dist/x86_64-linux/Cabal-1.22.7.0/build/autogen -g-i/home/jeremy/repos/haskell/distributed-process-lifted/src -g-i/home/jeremy/repos/haskell/distributed-process-lifted/test /home/jeremy/repos/haskell/distributed-process-lifted/src/Control/Distributed/Process/Lifted/Class.hs

0.03user 0.01system 0:00.10elapsed 51%CPU (0avgtext+0avgdata 30924maxresident)k
0inputs+0outputs (0major+8744minor)pagefaults 0swaps

```

Here using stack:

```shell
/usr/bin/time hdevtools check src/Control/Distributed/Process/Lifted/Class.hs

0.02user 0.01system 0:01.57elapsed 3%CPU (0avgtext+0avgdata 30856maxresident)k
0inputs+0outputs (0major+8724minor)pagefaults 0swaps
```

**Comment by ch1bo** [comment]
Yeah I heard it from others as well and wanted to investigate this. Do you have an idea why it takes longer?

**Comment by jeremyjh** [comment]
No, not yet; I do plan to investigate but wanted to post this first in case someone already knew what was causing it.

**Comment by ch1bo** [comment]
Ok, after adding several traces and prints I identified https://github.com/hdevtools/hdevtools/blob/master/src/Server.hs#L79 as the root of our problems. When creating a new config, `stack.yaml`s are searched in the given paths (e.g. "src/Main.hs"), package dbs are determined by executing `stack` and so on. 

So one solution could be to cache created configs from such `CommandExtra`s, although I'm not really happy with the config and session handling after reading the code. One can see how the code grew over time.

**Comment by jeremyjh** [comment]
I assumed it was something like this.  As I user I do not expect hdevtools to pickup changes in my stack file or package database while the server is running. And really it doesn't do that today even for sandbox projects; if you upgrade a dependency or add a new one you'll likely need to restart the server. So I expect it should cache all this information it gets from Stack just one time.

**Comment by ch1bo** [comment]
You are probably right..configuration changes could be more easily and consistently detected by observing changes to initially determined cabal/stack files. 

Btw: how do you feel about server lifetime and that it is tied to a socket file? I always wished for auto-shutdown after a reasonable idle time (plus there is a space leak somewhere, as hdevtools processes ate quite some memory after a couple of days developing).

**Comment by jeremyjh** [comment]
I submitted a PR with the simplest possible change to address this - it just caches the config after the first command execution; it works great for me - its fast like it is supposed to be now.
